FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}
RUN pip install poetry==1.8.5
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install --only main --no-root
COPY src ./src
ENV PYTHONPATH=${LAMBDA_TASK_ROOT}/src
CMD ["safety_database.lambda_handler.lambda_handler"]
