apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safety
  namespace: safety
spec:
  rules:
    - host: safety.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: safety-backend
                port:
                  number: 9000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: safety-frontend
                port:
                  number: 80
